server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          order: 1
          predicates:
            - Path=/user/**
        - id: project-service
          uri: lb://project-service
          order: 1
          predicates:
              - Path=/project/**
        - id: task-service
          uri: lb://task-service
          order: 1
          predicates:
              - Path=/task/**
        - id: project-member-service
          uri: lb://project-member-service
          order: 1
          predicates:
            - Path=/member/**
        - id: file-service
          uri: lb://file-service
          order: 1
          predicates:
              - Path=/file/**
        - id: landmark-service
          uri: lb://landmark-service
          order: 1
          predicates:
              - Path=/landmark/**
        - id: message-service
          uri: lb://message-service
          order: 1
          predicates:
            - Path=/message/**


      #     配置跨越
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]': # 匹配所有的请求路径
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5173"
              - "http://www.4399.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

dubbo:
  application:
    name: gateway-service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: -1

